import 'reflect-metadata'
import { Container } from '@freshgum/typedi'
import { DocumentMarkdownReader } from './DocumentMarkdownReader'
import './strategies/document/HtmlDocumentImportStrategy'
import './strategies/document/MarkdownDocumentImportStrategy'
import './strategies/document/OpenDocumentImportStrategy'
import './strategies/document/PagesDocumentImportStrategy'
import './strategies/document/PdfDocumentImportStrategy'
import './strategies/document/PlainTextDocumentImportStrategy'
import './strategies/document/RtfDocumentImportStrategy'
import './strategies/document/WordDocumentImportStrategy'

export const documentMarkdownReader = new DocumentMarkdownReader(Container)

export { DocumentImportStrategy } from './strategies/document/DocumentImportStrategy'
export { ImageStoringStrategy } from './strategies/images/ImageStoringStrategy'
export { DataUrlImageStoringStrategy } from './strategies/images/DataUrlImageStoringStrategy'
export { DocumentMarkdownReader } from './DocumentMarkdownReader'
export type { SupportedFormat } from './resolvers/DocumentReadStrategyResolver'
export type { DocumentReadOptions } from './types/DocumentReadOptions'
export { DocumentImportError } from './errors/DocumentImportError'
export { InvalidDocumentError } from './errors/InvalidDocumentError'
export { InvalidDocxError } from './errors/InvalidDocxError'
export { InvalidOdtError } from './errors/InvalidOdtError'
export { InvalidPagesError } from './errors/InvalidPagesError'
export { InvalidPdfError } from './errors/InvalidPdfError'
export { UnreadableDocumentError } from './errors/UnreadableDocumentError'
export { UnreadableDocError } from './errors/UnreadableDocError'
export { UnreadablePagesError } from './errors/UnreadablePagesError'
export { UnreadablePdfError } from './errors/UnreadablePdfError'
export { UnsupportedFormatError } from './errors/UnsupportedFormatError'

export type { DocumentFileLike } from './types/DocumentFileLike'
