name: Update Examples README

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - '!examples/README.md'
      - '.github/workflows/update-examples-readme.yml'
      - '.github/templates/examples-readme.md.ejs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-examples-readme:
    name: Update Examples README
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Collect example folders
        id: collect-folders
        env:
          GITHUB_REPO: ${{ github.repository }}
        run: |
          folders_json=$(find examples -mindepth 1 -maxdepth 3 -type d | sort | jq -R -s -c 'split("\n") | map(select(length > 0))')
          data=$(jq -cn --argjson folders "$folders_json" --arg github_repo "$GITHUB_REPO" '{ folders: $folders, github_repo: $github_repo }')
          echo "data=$data" >> "$GITHUB_OUTPUT"

      - name: Render examples README template
        id: render
        uses: kikyous/template-action@v2.0.0
        with:
          template-path: '.github/templates/examples-readme.md.ejs'
          ext-inputs: '${{ steps.collect-folders.outputs.data }}'

      - name: Write examples README
        env:
          README_CONTENT: ${{ steps.render.outputs.content }}
        run: echo "$README_CONTENT" > examples/README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: regenerate examples/README.md'
          file_pattern: 'examples/README.md'
